<div id="footer_wrapper">
    <div id="footer">
        <div id="tmfooterlinks">
            <div>
                <h4>Informacje</h4>
                    <ul>
                        <li><a href=""><span>Kontakt</span></a></li>
                        <li><a href=""><span>O nas</span></a></li>
                        <li><a href=""><span>Regulamin</span></a></li>
                    </ul>
            </div>
            <div>
                <h4>Oferta</h4>
                    <ul>
                        <li><a href=""><span>Nowe oferty</span></a></li>
                        <li><a href=""><span>Promocje</span></a></li>
                    </ul>
            </div>
            <div>
                <h4>Moje konto</h4>
                    <ul>
                        <li><a href=""><span>Ustawienia konta</span></a></li>
                    </ul>
            </div>
            <p>©2012 Powered by <a href="" title="">Infouslugi.pl</a>. Wszelkie prawa zastrzeżone. Zabrania się kopiowania i rozpowszechniania prezentowanych materiałów.</p>
            <div class="licznik">
                <span class="inscription">Odwiedziny</span>
                <div class="number"></div>
            </div>
        </div>
    </div>
</div>
